AWSTemplateFormatVersion: 2010-09-09
Description: ECS Infrastructure Interview Template 1
Parameters:
Resources:
  rLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: rLambdaFunctionRole
      Path: /
      Policies:
        - PolicyName: allow-ec2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - ec2:*
              Effect: Allow
              Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/AmazonGlacierFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
Outputs:
  rLambdaFunctionRoleARN:
    Description: "rLambdaFunctionRole ARN"
    Value: !GetAtt rLambdaFunctionRole.Arn    
    Export: 
      Name: !Sub "${AWS::StackName}-FunctionRoleARN"     